### ISSUE TITLE
cant get it to work

### ISSUE THREAD

**Issue by CrownScorpion** [zatrit/funny-projector#1]
I downloaded your mod on thunderstore and dispite many attempts to get it working i have had no luck. With the setting "vanilla only" true or false it still only shows base game green screen backgrounds. Here is an image of how i have the backgrounds txt file maybe im doing something wrong but i cant get any custom image to appear in game.
![image3](https://github.com/zatrit/funny-projector/assets/96143117/3f7dfc73-7e2c-454b-969e-55d0ac9c7143)

**Comment by AshyDisaster** [comment]
Can + to this; launched the game and it didn't make the backgrounds config so I had to make one myself. I have a png and a jpg and it doesn't seem to be showing either. Using r2modman. Not even the fallback png I can find anywhere else

**Comment by zatrit** [comment]
Is there any errors in logs?
Upd: I think that mod somehow can't set a list of textures or send a request for it.

**Comment by CrownScorpion** [comment]
is it something we can fix or something you have to update to fix

**Comment by zatrit** [comment]
Send me your logs, because I really don't know what went wrong. My previous post is just a theory

**Comment by CrownScorpion** [comment]
sure i can do that here in a min what logs would you need ill also send any images of errors in the console if there is any

**Comment by zatrit** [comment]
The main BepInEx log file is `BepInEx/LogOutput.txt `

**Comment by CrownScorpion** [comment]
> The main BepInEx log file is `BepInEx/LogOutput.txt `

i have LogOutput.log but its a day old. I did just launch the game and there was a few errors related to your mod i will send the pictures of the errors in console.

**Comment by CrownScorpion** [comment]
![funny error1](https://github.com/zatrit/funny-projector/assets/96143117/3c071188-473c-4123-83be-a6236c60c8ec)
![funny error2](https://github.com/zatrit/funny-projector/assets/96143117/16b5fbfa-a058-4b39-8ed7-f91a9a969915)

**Comment by zatrit** [comment]
I found a way to fix the second error

**Comment by CrownScorpion** [comment]
nice what about the first any luck?

**Comment by zatrit** [comment]
Seems to be fixed in 1.0.4
Upd: please, check is it works for you

**Comment by CrownScorpion** [comment]
sure i can right now 
EDIT: it works only the image i put showed up.

**Comment by zatrit** [comment]
Is ``Keep vanilla`` enabled?

**Comment by CrownScorpion** [comment]
no i will enable it and test that.
EDIT: it works it was at the end of all the vanilla ones.

**Comment by CrownScorpion** [comment]
one question tho any way you could get a .gif to work?

**Comment by zatrit** [comment]
Currently no any

**Comment by AshyDisaster** [comment]
> Seems to be fixed in 1.0.4 Upd: please, check is it works for you

![Content_Warning_37xlozw75E](https://github.com/zatrit/funny-projector/assets/150559169/6fc4c9f5-cbb7-49ef-bb30-ff0481d99b05)
Works now, thanks!
